spring.application.name=Login-Seguro

# Banco
spring.mongodb.database=login_seguro

spring.config.import=optional:file:.env[.properties]

# Conexão com o MongoDB
spring.mongodb.uri=${MONGODB_URI}

# Porta
server.port=8080